Fiorello/Fiorello/Models/Blog.cs
using System;

namespace Fiorello.Models
{
    public class Blog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public DateTime CreatedTime { get; set; }
    }
}

Fiorello/Fiorello/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fiorello.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Fiorello/Fiorello/ViewComponents/BlogViewComponent.cs
using Fiorello.DAL;
using Fiorello.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fiorello.ViewComponents
{
    public class BlogViewComponent : ViewComponent
    {
        private readonly AppDbContext _db;

        public BlogViewComponent(AppDbContext db)
        {
            _db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync(int take)
        {
            List<Blog> blogs = new List<Blog>();

            if (take == 3)
            {
                blogs = await _db.Blogs.OrderByDescending(x=>x.Id).Take(take).ToListAsync();
            }
            else
            {
                blogs = await _db.Blogs.OrderByDescending(x => x.Id).ToListAsync();

            }

            return View(blogs);
        }
    }
}

Fiorello/Fiorello/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Blog";
}
<section id="shop-list-title">
<div class="container py-4">
    <div class="row py-5">
        <div class="col-12">
            <h1>Blog</h1>
        </div>
    </div>
</div>
</section>

<!-- BLOG START -->

<section id="blog">
    <div class="container">
        <div class="row py-5">
            <div class="offset-lg-3 col-lg-6">
                <div class="section-title">
                    <h1>From our Blog</h1>
                    <p class="text-black-50">
                        A perfect blend of creativity, energy, communication, happiness and
                        love. Let us arrange
                        a smile for you.
                    </p>
                </div>
            </div>
        </div>
        <div class="row pb-5">
            @await Component.InvokeAsync("Blog",new{take=0})
        </div>
    </div>
</section>

<!-- BLOG END -->
<!-- INSTAGRAM START -->

<section id="instagram">
    <div class="owl-carousel instagram">
        <div><img src="~/img/instagram1.jpg" class="img-fluid" alt=""></div>
        <div><img src="~/img/instagram2.jpg" class="img-fluid" alt=""></div>
        <div><img src="~/img/instagram3.jpg" class="img-fluid" alt=""></div>
        <div><img src="~/img/instagram4.jpg" class="img-fluid" alt=""></div>
        <div><img src="~/img/instagram5.jpg" class="img-fluid" alt=""></div>
        <div><img src="~/img/instagram6.jpg" class="img-fluid" alt=""></div>
        <div><img src="~/img/instagram7.jpg" class="img-fluid" alt=""></div>
        <div><img src="~/img/instagram8.jpg" class="img-fluid" alt=""></div>
    </div>
    <div class="hastag bg-light text-muted py-2 px-3">
        #FIORELLO
    </div>
</section>

<!-- INSTAGRAM END -->