Fiorello/Fiorello/Models/About.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Net.NetworkInformation;

namespace Fiorello.Models
{
    public class About
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }
    }
}

Fiorello/Fiorello/Areas/Admin/Controllers/AboutController.cs
using Fiorello.DAL;
using Fiorello.Helper;
using Fiorello.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System.Threading.Tasks;

namespace Fiorello.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AboutController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _env;

        public AboutController(AppDbContext db,IWebHostEnvironment env)
        {
            _env = env;
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            About about = await _db.About.FirstOrDefaultAsync();
            return View(about);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
                return NotFound();
            About about = await _db.About.FirstOrDefaultAsync(x=>x.Id == id);
            if (about == null)
                return BadRequest();

            return View(about);
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return NotFound();
            About dbabout = await _db.About.FirstOrDefaultAsync(x=>x.Id==id);
            if(dbabout==null)
                return BadRequest();

            return View(dbabout);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Update(int? id,About about)
        {
            if (id == null)
                return NotFound();
            About dbabout = await _db.About.FirstOrDefaultAsync(x=>x.Id==id);
            if(dbabout==null)
                return BadRequest();

            #region Photo
            if(about.Photo != null)
            {
                if (!about.Photo.IsImage())
                {
                    ModelState.AddModelError("Photo", "Just Select image type!");
                    return View();
                }

                if(about.Photo.IsOlder216Kb())
                {
                    ModelState.AddModelError("Photo", "Max 216Kb");
                    return View();
                }

                string folder = Path.Combine(_env.WebRootPath, "img");
                about.Image = await about.Photo.SaveFileAsync(folder);
                string path = Path.Combine(_env.WebRootPath, folder, dbabout.Image);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
                dbabout.Image = about.Image;
            }
            #endregion

            dbabout.Title = about.Title;
            dbabout.Description = about.Description;

            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Fiorello/Fiorello/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fiorello.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Fiorello/Fiorello/ViewComponents/AboutViewComponent.cs
using Fiorello.DAL;
using Fiorello.VIewsModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Linq;
using System.Threading.Tasks;

namespace Fiorello.ViewComponents
{
    public class AboutViewComponent : ViewComponent
    {
        private readonly AppDbContext _db;

        public AboutViewComponent(AppDbContext db)
        {
            _db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            HomeVM homeVM = new HomeVM
            {
                About = await _db.About.FirstOrDefaultAsync(),
                AboutInfo = await _db.AboutInfo.Take(3).Where(x=>!x.IsDeactive).ToListAsync()
            };

            return View(homeVM);
        }
    }
}

Fiorello/Fiorello/Views/About/Index.cshtml
@{
    ViewBag.Title = "About";
}
<section id="shop-list-title">
    <div class="container py-4">
        <div class="row py-5">
            <div class="col-12">
                <h1>About</h1>
            </div>
        </div>
    </div>
</section>

<!-- ABOUT START -->

        <section id="about">
            <div class="container py-5">
                <div class="row py-5">
                    @await Component.InvokeAsync("About")
                </div>
            </div>
        </section>

        <!-- ABOUT END -->


     <!-- EXPERTS START -->

        <section id="experts">
            <div class="container">
                <div class="row py-5">
                    <div class="offset-lg-3 col-lg-6">
                        <div class="section-title">
                            <h1>Flower Experts</h1>
                            <p class="text-black-50">A perfect blend of creativity, energy, communication, happiness and
                                love. Let us arrange
                                a smile for you.</p>
                        </div>
                    </div>
                </div>
                <div class="row pb-5">
                    <div class="col-md-6 col-lg-3">
                        <div class="item text-center">
                            <div class="img">
                                <img src="~/img/h3-team-img-1.png" class="img-fluid rounded-circle" alt="">
                            </div>
                            <div class="text mt-3">
                                <h6>CRYSTAL BROOKS</h6>
                                <p class="text-black-50">Florist</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="item text-center">
                            <div class="img">
                                <img src="~/img/h3-team-img-2.png" class="img-fluid rounded-circle" alt="">
                            </div>
                            <div class="text mt-3">
                                <h6>SHIRLEY HARRIS</h6>
                                <p class="text-black-50">Manager</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="item text-center">
                            <div class="img">
                                <img src="~/img/h3-team-img-3.png" class="img-fluid rounded-circle" alt="">
                            </div>
                            <div class="text mt-3">
                                <h6>BEVERLY CLARK</h6>
                                <p class="text-black-50">Florist</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="item text-center">
                            <div class="img">
                                <img src="~/img/h3-team-img-4.png" class="img-fluid rounded-circle" alt="">
                            </div>
                            <div class="text mt-3">
                                <h6>AMANDA WATKINS</h6>
                                <p class="text-black-50">Florist</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3"></div>
                </div>
            </div>
        </section>

        <!-- EXPERTS END -->